# Generated by Django 4.1.1 on 2022-11-20 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_relationship_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='relationship',
            managers=[
            ],
        ),
    ]
