# Generated by Django 4.1.1 on 2022-11-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_relationship_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ava_pic',
            field=models.ImageField(default='static/default_ava.png', upload_to='profile'),
        ),
    ]
