# Generated by Django 4.1.1 on 2022-11-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_profile_ava_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ava_pic',
            field=models.ImageField(default='default_ava.png', upload_to='profile'),
        ),
    ]
